### ISSUE TITLE
Faster 'convert_fasta' and 'as_bam'

### ISSUE THREAD

**Issue by superbobry** [brentp/bwa-meth#11]
These two seem to be the bottlenecks during alignment. Have you considered using Cython or C/C++ to speed things up?

**Comment by superbobry** [comment]
I've recently used `bwa-mem` for aligning unpaired reads and noticed a slowdown on the Python a side. I'm thinking that treating paired and unpaired reads separately in `convert_reads` might help, because all of the operations below are useless for the unpaired case:

```python
for read_i, (name, seq, _, qual) in enumerate(pair):
    if name is None: continue
    name = name.rstrip("\r\n").split(" ")[0]  # except for this line.
    if name.endswith(("_R1", "_R2")):
         name = name[:-3]
    elif name.endswith(("/1", "/2")):
        name = name[:-2]
```

What do you think?

**Comment by brentp** [comment]
If you benchmark and see a significant improvement from that change, I'd accept. Maybe this:

```Python
for pair in izip(q1_iter, q2_iter)
```

could be

```Python
qiter = izip(q1_iter, q2_iter) if fq2 != "NA" else q1_iter
```
then loop over that and it could remove some of the internal checks.

I'd guess that the slowdown might be in processing the bam rather than converting the FASTQ
