### ISSUE TITLE
running bwameth.py tabulate on Ecoli data

### ISSUE THREAD

**Issue by avilella** [brentp/bwa-meth#17]
Hi,

I am running `bwameth.py tabulate` on an Ecoli bisulfite treated sample aligned with bismark/bowtie2.

I was getting no methylation calls with the default parameters, so I changed to `--context all` and ran a parameter sweep on the `--map-q` option. If I run this on the first 1000bp of the Ecoli genome, I get no calls for mapq values ranging from 60-43, but then I get 138 lines in the meth.vcf file from map-q 42 downwards.

Any ideas what would be a good way of running bwameth/BisSNP on Ecoli data like this?

I read a paper that says Ecoli methylation is found in around 1-2 cases every 1000bp for the CmCWGG motif, but I am unsure how to specify that in BisSNP. Is it possible?

**Comment by brentp** [comment]
I think it's better to use something like [PileOMeth](https://github.com/dpryan79/PileOMeth) or maybe [biscuit](https://github.com/zwdzwd/biscuit) if you have trouble with `tabulate_methlation` since it's just a thin wrapper around BisSNP.
