### ISSUE TITLE
[fputs] Broken pipe

### ISSUE THREAD

**Issue by acgtun** [brentp/bwa-meth#18]
I got this several error when run BWA-METH.

/haifengc/panfs/bireads/SRR1171540_1_1000000.fastq NA'
writing to:
samtools view -bS - | samtools sort - bwa-meth
[M::bwa_idx_load_from_disk] read 0 ALT contigs
converting reads in /home/rcf-40/haifengc/panfs/bireads/SRR1171540_1_1000000.fastq,NA
WARNING: running bwameth in single-end mode
[M::process] read 666668 sequences (60000120 bp)...
[M::process] read 333332 sequences (29999880 bp)...
[M::mem_process_seqs] Processed 666668 reads in 316.005 CPU sec, 319.250 real sec
Traceback (most recent call last):
  File "bwameth.py", line 601, in <module>
    main(sys.argv[1:])
  File "bwameth.py", line 586, in main
    set_as_failed=args.set_as_failed)
  File "bwameth.py", line 259, in bwa_mem
    as_bam(cmd, fa, prefix, calmd, set_as_failed)
  File "bwameth.py", line 299, in as_bam
    out.write(str(aln) + '\n')
IOError: [Errno 32] Broken pipe
[fputs] Broken pipe

**Comment by brentp** [comment]
can you send a small fastq to re-create?

**Comment by acgtun** [comment]
@SRR1171540.1 FCD14TWACXX:1:1101:1440:2156 length=90
GAGGTAGGAGAATTATTTGAATTTAGGAAGTGGAAGTTAGTGAGTCGAGATCGTGTTATTGTATTATAGTTTAGGCGATAGAGTAAGATT
+SRR1171540.1 FCD14TWACXX:1:1101:1440:2156 length=90
_bbecdcecggggiehiiifbghi_ghbghebfX^^^dfe^cfgeggegZ^ffee^b`g`febegdfbgfdhbdffddaaa_b]Y_b``c
@SRR1171540.2 FCD14TWACXX:1:1101:1399:2172 length=90
AGTGATATAGAGTTTTGGGTTATTTGTTTATGTAGTTTATTTATGTTTTTTGGTTTTTTTGGATTAAATTTTAAATTTATTATTTTTATT
+SRR1171540.2 FCD14TWACXX:1:1101:1399:2172 length=90
_bbececeeecgcfghiiibfbfhiibfgfhhh_f^effhihfhgfhiiiihdbghiiigec_dc_Z]bcdc`]`Z_bcccbceddc_cc
@SRR1171540.3 FCD14TWACXX:1:1101:1498:2200 length=90
GTTTTAATATTTTAATATTATTTTATTTTTTTTATTAATATAAGAAGGTAGGAATGTTTAGTTTTTGAGTTTAAGTTAAGTTATTGTATT
+SRR1171540.3 FCD14TWACXX:1:1101:1498:2200 length=90
bbbeeeeegeeggfffhhhfhfiifhiihiiiicghfdgbhhhfceeg^cbbW\be_egdbNV\bfd`d^dc]]Zbdbbbcccddcbbba
@SRR1171540.4 FCD14TWACXX:1:1101:1395:2217 length=90
AGTTTTTTAAGTAGTTGGGATTGTAGGTATGTGTATTATATTTGGTTAATATTTTAGTTTTTGTAGAAATAGGGTTTTTTTGTGTTGTTT
+SRR1171540.4 FCD14TWACXX:1:1101:1395:2217 length=90
_b_ceeeecage`ffghiiacdfd[egb_fgceb[bf]e_ffiiic`d_f`fdhhfe^efg`ffbe`e_dZbghH\^bcccccccccccc
@SRR1171540.5 FCD14TWACXX:1:1101:1351:2235 length=90
ATAGATTAGTAAAATATTATTTTAAGTGTTTTTTTATGTTTTAATTTGAATTTTTTTTTTGTTTTAATTGTAATAGTTATGGTAATTATT
+SRR1171540.5 FCD14TWACXX:1:1101:1351:2235 length=90
ab_eceeeggeccdgfhiihiiiddgbebefghhhXaffhhhfafghhdXceeegfggab]K\bc`T]bb`_GZRT]a``b`]`]`b]_b
@SRR1171540.6 FCD14TWACXX:1:1101:1735:2131 length=90
TATTTATAGTTTGTTATTTTTAGGGGATTAAGTTGGGAAGTTGAGTGGTTAATGATTGAGTTGTTTTAAATAGTTGGGTATTTAGTTAAT
+SRR1171540.6 FCD14TWACXX:1:1101:1735:2131 length=90
bbbeeeeegggggghiiiiiihhiiieghhigghgiibfg^egegacf^cebgfcehgabWaebfhff__cdb_`^bd^_acebbbb]Z_
@SRR1171540.7 FCD14TWACXX:1:1101:1605:2131 length=90
TTAAAAGTTATTATTTATTTTTTAGAAATTTTTGTATAAATTATTTTTTAATTTGTATGTGTTTAAAGTAGATATAAATGATTGTAAAAT
+SRR1171540.7 FCD14TWACXX:1:1101:1605:2131 length=90
_b_eeeecgfgggiiihiiiiiihihhhiiihiigfhfhhhihhhiiiiihihiigfhhghefhhfdcadccgfgeaggggeeeee_`bb
@SRR1171540.8 FCD14TWACXX:1:1101:1577:2173 length=90
ATTATGGGTTAGGTTTTGGATTTTAGAGGTGAAAGTTGGGAGTGGAGAATTGTATTTGTAAATTTTGTTTTTTGGTTTTTTTGAAAGAGT
+SRR1171540.8 FCD14TWACXX:1:1101:1577:2173 length=90
_bbeeeeecgaggeghfhiagghg_e_egPbb`]eY^eghZeO^c[ccZe`eWSae\b\_`Zedddfgfhgge`]acaccca]WYRYX`b
@SRR1171540.9 FCD14TWACXX:1:1101:1711:2174 length=90
TTTATAGGAGTTTTATTTTTTGGTATAAGTAAGGATGATATTGGGAGTATTTTTTAAAGTAGTATTTTTTTGAGGGAAAGTGATAGTAGG
+SRR1171540.9 FCD14TWACXX:1:1101:1711:2174 length=90
bbbeeeeccegcgihihihhefaebgedgafgfba^ccfafhiehdeN^[chhhib_`bddc\bdg_gdcbc^\^\FTXX]``b`bbc`b
@SRR1171540.10 FCD14TWACXX:1:1101:1639:2215 length=90
TTTATGTGGTAAATAAATTGGTTGTTTTGAATTTTGCTAATTTGGGAGGAGATGGGTTTTTTTGGGTTTTTTGTTTTAGTTATGGTTTGG
+SRR1171540.10 FCD14TWACXX:1:1101:1639:2215 length=90
abbeeecegegggiiihiiiihfhegiiifdgiiihhghfhihiiicfh^e^ccghWZ_cbgedbc\^_^aaa^b[bb^bb`cbcbcccc

**Comment by acgtun** [comment]
The above is the first 10 reads

**Comment by brentp** [comment]
I don't get an error with those. Can you tell me the result of: `bwa 2>&1 | head -5`

**Comment by acgtun** [comment]
Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.12-r1044
Contact: Heng Li <lh3@sanger.ac.uk>

**Comment by brentp** [comment]
what reference are you using?

**Comment by acgtun** [comment]
UCSC hg19

**Comment by brentp** [comment]
can you paste the full command that  you are using and the full resulting error?
do you get an error with the 10 reads that you pasted?

**Comment by acgtun** [comment]
maybe the error was not in the first 10 reads
