### ISSUE TITLE
adding passing options to bwa mem

### ISSUE THREAD

**Issue by avilella** [brentp/bwa-meth#20]
When I run bwa-meth, it calls bwa-mem with these parameter set:

`bwa mem -T 40 -B 2 -L 10 -CM`

Would it be possible to pass-through the -T/B/L options to the script to tune it to the desired options by the user?

**Comment by brentp** [comment]
Yeah, I should add this, but didn't want to replicate all of the options. For now, you can just edit bwa-meth.py directly.
I found that changing those doesn't affect the results much, but I wanted to have higher penalties.

**Comment by avinashs** [comment]
Follow up question on this old issue.. but curious if you had a specific reasoning for fixing the default penalties that you did. Particularly, it seems like bwa-meth is highly incentivized to allow mis-matches in an alignment than resort to clipping. Is there something inherent about Bisulphite sequencing data that requires that clipping should be discouraged? Or was it just a heuristic? Thanks!

**Comment by brentp** [comment]
I can't remember why I did this, but it's possible to send your own arguments via the command line to override the defaults. The penalties I made up are not that different from bwa mem defaults so I doubt it matters much.
