### ISSUE TITLE
bed file

### ISSUE THREAD

**Issue by Fabunanr** [brentp/bwa-meth#23]
What does "pct" mean?

how can I tell which site is methylated?

**Comment by superbobry** [comment]
> What does "pct" mean?

I think *pct* stands for percentage of C to C + T and is otherwise known as "methylation level". 

> how can I tell which site is methylated?

You need statistics to do that reliably, e.g. you can simply threshold "pct".

**Comment by brentp** [comment]
I would also mention to use https://github.com/dpryan79/PileOMeth
for extraction after mapping with bwa-meth, rather than relying on the scripts here. Those are more actively developed.
