### ISSUE TITLE
samtools goes awol

### ISSUE THREAD

**Issue by JohnLonginotto** [brentp/bwa-meth#24]
Hey Brent :D

So it seems after bwa-meth's bias-plot has finished running, writes it's output and closes, "samtools view -F4" continues to hang around reading the file (presumably until the end) and not close?

I guess the bias plot takes a sample of the data and not all the data when creating it's plot (because it's so quick) - so i guess samtools should close down too once its done :)

Perhaps there could be an --all flag when running the bias-plot to check all the reads? I'm a little nervous about subsamples, particularly on sorted data. All the best, and again thank you so much for this awesome mapper :)

**Comment by brentp** [comment]
Hi, I'm not getting notifications of new issues for some reason, hence the delay.

I recommend to use bwa-meth for mapping and then use @dpryan79 's https://github.com/dpryan79/PileOMeth for extraction, plotting, etc. I'll leave this issue open until I update the readme.

**Comment by JohnLonginotto** [comment]
No worries brentp, I appreciate that maintaining all the software you put out is no small feat! I'm amazed you find the time to do it at all :)

I did in fact use Devon's PileOMeth tool, specifically the indel realigner, and it all worked really really nicely. However, PoM does not do SNP calling, which i'm using bwa-meth/BisSNP for. This is unrelated to the above issue, but bwa-meth's tabulate has options I can't find any documentation on, specifically --region and --context. I have my targets from @dpryan's indel realigner - is that what i'm supposed to use in --region? Thanks for you time!

John

**Comment by brentp** [comment]
I updated the readme to point to alternatives. the `--region` is just a region of the genome, e.g. 'chr1:1-99999' so that it makes the script easy to parallelize by sending each part a different region.

But, you can try out  [biscuit](https://github.com/zwdzwd/biscuit) for the SNP calling if you keep having troubles with the script here. It likely has some bit rot.
