### ISSUE TITLE
unmapped reads in c2t converted

### ISSUE THREAD

**Issue by jklughammer** [brentp/bwa-meth#28]
Hi,
it seems that bwameth.py only reverts the mapped reads back to their original state, while unmapped reads are reported in their c2t converted form in the aligned bam file.
Is this the desired behavior? For my application it would be crucial to get the original reads from the bam file also for the unmapped reads.
Is there a way to do this?
Thanks!

**Comment by jklughammer** [comment]
commenting out lines 346 and 347 in bwameth.py seems to solve the problem. These lines look a lot like a remnant especially because reads are being checked for being unmapped again later. Could you please confirm that these lines aren't actually needed?

**Comment by brentp** [comment]
that looks right. please open a pull-request.
