### ISSUE TITLE
Push out a new release?

### ISSUE THREAD

**Issue by dpryan79** [brentp/bwa-meth#33]
It'd be nice to add this to bioconda and Galaxy. For that, it'd be nice to include a version that's not from 2014 :) If you take care of the new release, I'll see to it getting added to bioconda and Galaxy.

**Comment by brentp** [comment]
I just tagged v0.2.0. Would be great to get it into bioconda and galaxy. Thanks Devon.

**Comment by dpryan79** [comment]
Great! I'm working on the wrappers and such now.
