### ISSUE TITLE
--prefix spec in docs breaks bwameth due to new opts pass through functionality

### ISSUE THREAD

**Issue by swingingsimian** [brentp/bwa-meth#35]
Morning Brent

I think the README for v0.2.0/master is a little out of date. I'm assuming you dropped the --prefix and bai indexing support from bwameth.py , as when I specify --prefix as the README suggests, this is no longer recognised by bwameth.py.  And due to the new opt passthrough functionality it's passed through to bwa mem, as which point I get the following error:

```
mem: invalid option -- '-'
```

Also the installation instructions are a little out of date, reference v0.10.0 instead of v0.2.0.

I would have simply issued a pull request on the README, but I wasn't sure about the wider considerations with the latest release, so thought it best to leave it with you.

When I get time, I will try and tighten up the option pass through to make it more explicit using something like --bwa_mem_opts.

Thanks

Nathan

**Comment by brentp** [comment]
Thanks for pointing this out.
I think in this case, the best thing is to update the docs. The pass-through makes sense as-is--you get a moderately informative message. 
Let's plan to update the docs.
