### ISSUE TITLE
README update, confused about output

### ISSUE THREAD

**Issue by evanbiederstedt** [brentp/bwa-meth#36]
Hi everyone,

Thanks for the excellent tool!

(1) Could you update the README so the `--prefix` flag isn't shown? I missed the note above following the examples; it would help productivity if you just created a "legacy code" section or eliminate all references to `--prefix` all together

(2) I'm a bit confused, as it appears that I do not have an output for `bwameth.py --reference ref.fa t_R1.fastq.gz t_R2.fastq.gz -t X `. 

When running this command, I see the output using `bwa mem` with the last item as `NA`. Normally, if I were to use bwa mem alone, I would pipe this to an output. When running `bwameth.py --reference ref.fa t_R1.fastq.gz t_R2.fastq.gz -t X ` as in the example https://github.com/brentp/bwa-meth/tree/master/example/, how exactly do I access the output?

**Comment by brentp** [comment]
I updated the readme.  I'm not sure I understand (2).

If I do:
```
cd examples/
python ../bwameth.py --reference ref.fa t_R1.fastq.gz t_R2.fastq.gz -t 5 > s.sam
samtools view -b s.sam > s.bam
```

I see no problems, and I get a sam and then bam file with the expected output. Can you clarify the problme that you are having?

**Comment by evanbiederstedt** [comment]
Sorry---I could have been more clear myself. 

I think the example in https://github.com/brentp/bwa-meth/tree/master/example/ is unclear for those uninitiated with the underlying bwa mem code outputting to stdout. 

In the tutorial, you show

    bwameth.py index ref.fa
    bwameth.py --reference ref.fa t_R1.fastq.gz t_R2.fastq.gz -t 12

It might be more useful for first time users to show this

    bwameth.py index ref.fa
    bwameth.py --reference ref.fa t_R1.fastq.gz t_R2.fastq.gz -t 12 > myfile.sam
   

Right? Otherwise users just running a python script may expect an output file in whichever subdirectory they're running the script.

**Comment by brentp** [comment]
updated. thanks.

**Comment by evanbiederstedt** [comment]
Thanks for the help!
