### ISSUE TITLE
WARNING: 5355 reads with length < 80: this program is designed for long reads.

### ISSUE THREAD

**Issue by mu1197781069** [brentp/bwa-meth#39]
Hello Brent,

I make  simulation fastq files and then use bwa-meth to calculate methylation rate. First, i simulate RRBS reads. Second, i trim those RRBS reads using trim_galore. Then i use bwa-meth to calculate the methylation rate. But after running bwameth.py, it says 

WARNING: 5355 reads with length < 80
       : this program is designed for long reads

Could you be kind enough to help me solve this problem ?

Thanks

**Comment by brentp** [comment]
that's just a warning. you should still have output, but bwa-meth uses `bwa mem` which is best on long reads.

**Comment by mu1197781069** [comment]
Yes, i have an .bam output. But when i use pileOMeth, i get .bedGraph file. The file says 

track type="bedGraph" description="pileometh.sample20360.result CpG methylation levels"
