### ISSUE TITLE
ERNE-BS5

### ISSUE THREAD

**Issue by lmanchon** [brentp/bwa-meth#40]
--Hi,

is Bwa-Meth use a similar algorithm as ERNE-BS5 (https://sourceforge.net/projects/erne/) ?
And is somebody has already try to align and tabulate Bs-seq reads with Bwa-Meth and then use to-mr from MethPipe (https://github.com/smithlabcode/methpipe)   ?

thank you --

**Comment by brentp** [comment]
> is Bwa-Meth use a similar algorithm as ERNE-BS5 (https://sourceforge.net/projects/erne/) ?

I don't think so.

> And is somebody has already try to align and tabulate Bs-seq reads with Bwa-Meth and then use to-mr 
> from MethPipe (https://github.com/smithlabcode/methpipe) ?

There could be people doing that, but I still recommend to use PileOMeth
