### ISSUE TITLE
SNP Question

### ISSUE THREAD

**Issue by tantrev** [brentp/bwa-meth#43]
Just wondering if the bam file generated by bwa-meth file can be used directly in other SNP callers like biscuit?  My (naive) self is just curious since bwa-meth performs the C -> T conversion to speed up alignment.

**Comment by brentp** [comment]
Yes, the should be usable. It converts C->T for alignment, but then writes out the original read.

**Comment by tantrev** [comment]
Perfect, thank you!

**Comment by tantrev** [comment]
On a related note, do you by chance have any thoughts on the proper way to extract discordant and split reads from WGBS data?  I've been trying different methods and have gotten drastically different results, as outlined in this [lumpy](https://github.com/arq5x/lumpy-sv/issues/193) ticket.

**Comment by brentp** [comment]
the discordant flag isn't reliable from bwa meth (and therefore the flag isn't useful). It updates what it thinks is discordant within each processing chunk. So best to use lumpy_filter or something other than the flag.

**Comment by tantrev** [comment]
@brentp - thank you!  I'm not quite sure how to invoke the lumpy_filter, but I'll try posting in that lumpy ticket to see if anybody has any ideas.
