### ISSUE TITLE
-p flag

### ISSUE THREAD

**Issue by nchernia** [brentp/bwa-meth#50]
When paired end files are sent in as 

bwameth.py --reference hg19.fasta test_R1.fastq test_R2.fastq > test.sam

The output starts with: 
running: bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p ...

The -p flag is incorrect.  According to BWA:

If mates.fq file is absent and option -p is not set, this command regards input reads are single-end. If mates.fq is present, this command assumes the i-th read in reads.fq and the i-th read in mates.fq constitute a read pair. If -p is used, the command assumes the 2i-th and the (2i+1)-th read in reads.fq constitute a read pair (such input file is said to be interleaved). In this case, mates.fq is ignored. In the paired-end mode, the mem command will infer the read orientation and the insert size distribution from a batch of reads.

**Comment by nchernia** [comment]
Actually I see that you are interleaving upon reading?

**Comment by brentp** [comment]
yes, bwa-meth converts the reads in silico and sends them to that bwa mem process.
