### ISSUE TITLE
Question: multimapping handling

### ISSUE THREAD

**Issue by OnlyHigh** [brentp/bwa-meth#66]
Hello there, 
Quick question, how does bwa-meth handles reads multimapped?, for examples, reads mapping to transposable elements. 

Cheers, 
Luis Alfonso.

**Comment by brentp** [comment]
multi-mapped reads will have a lower mapping quality from bwa-mem, often zero. bwa-meth doesn't do anything beyond that

**Comment by OnlyHigh** [comment]
Thanks for the quick answer!, 
I'll have it into account when I'm extracting the methylations

**Comment by OnlyHigh** [comment]
Sorry, to bother again, 
I would like to know if multimapped reads are reported by choosing one location randomly or for all locations they map

**Comment by brentp** [comment]
this is handled by bwa-mem. you can look there for the details. my understanding is that it will report the first $n with a mapping quality of 0.
