### ISSUE TITLE
bwa-meth index error

### ISSUE THREAD

**Issue by almanza-d** [brentp/bwa-meth#76]
I kept getting an error when running the indexing through the bwa-meth pipelien:

`toolshed.files.ProcessException: bwa index -a bwtsw`

When running independently the underlying command in bwa-meth, i.e. `bwa index -a bwtsw *fa.bwameth.c2t`, indexing works fine. 

Any insight into this error?

**Comment by brentp** [comment]
Hi, can you show the full command and the full output?

**Comment by brentp** [comment]
It could be that you don't have write permission in the directory where the fasta files are located.

**Comment by almanza-d** [comment]
Here is the output:

```
converting c2t in hg19_lambda_puc19.fa to hg19_lambda_puc19.fa.bwameth.c2t
indexing with bwa-mem: hg19_lambda_puc19.fa.bwameth.c2t
[bwa_index] Pack FASTA... 43.38 sec
[bwa_index] Reverse the packed sequence... 17.29 sec
[bwa_index] Construct BWT for the packed sequence...
TextLengthFromBytePacked(): text length > 2^32!
cmd was:bwa index -a bwtsw hg19_lambda_puc19.fa.bwameth.c2t
return code was:1
Traceback (most recent call last):
  File "/drive3/dalmanza/software/bwa-meth/bwameth.py", line 559, in <module>
    main(sys.argv[1:])
  File "/drive3/dalmanza/software/bwa-meth/bwameth.py", line 510, in main
    sys.exit(bwa_index(convert_fasta(args[1])))
  File "/drive3/dalmanza/software/bwa-meth/bwameth.py", line 225, in bwa_index
    run("bwa index -a bwtsw %s" % fa)
  File "/drive3/dalmanza/software/bwa-meth/bwameth.py", line 97, in run
    list(nopen("|%s" % cmd.lstrip("|")))
  File "/home/diehnlab/dalmanza/.conda/envs/Diego/lib/python3.7/site-packages/toolshed/files.py", line 61, in process_iter
    raise ProcessException(cmd)
toolshed.files.ProcessException: bwa index -a bwtsw hg19_lambda_puc19.fa.bwameth.c2t
```

**Comment by brentp** [comment]
does `hg19_lambda_puc19.fa` contain more than 4GB of sequence? It seems so.

**Comment by almanza-d** [comment]
Does not seem like it.

```
3.0G	hg19_lambda_puc19.fa
```

**Comment by brentp** [comment]
and how big is the c2t file?

**Comment by almanza-d** [comment]
```
6.0G	hg19_lambda_puc19.fa.bwameth.c2t
```

**Comment by brentp** [comment]
can you show the content of `hg19_lambda_puc19.fa.fai` ?

**Comment by brentp** [comment]
and make sure you have the newest version of bwa installed?

**Comment by brentp** [comment]
and can you show the full command that you are running and the full output.

**Comment by brentp** [comment]
ok. it looks like you just need to update your version of bwa. you can see latest release here: https://github.com/lh3/bwa/releases/tag/v0.7.17
