### ISSUE TITLE
`handle_header` mangles alt contigs

### ISSUE THREAD

**Issue by jdidion** [brentp/bwa-meth#79]
When using a reference with alt contigs, contigs with names of the form "HLA-A*01:01:01:01" are truncated to "HLA-A*01", which produces duplicate contig names in the output. If bwa-meth is not designed to work with alt contigs, please state this explicitly in the readme, otherwise this issue needs to be addressed. Thanks.

**Comment by jdidion** [comment]
My guess is that this is unintentional and can be fixed by adding `maxsplit=1`. I'll submit a PR.

**Comment by brentp** [comment]
closed by #80
