### ISSUE TITLE
when running bwameth example, exception: AttributeError: module 'toolshed.files' has no attribute 'prefunc'

### ISSUE THREAD

**Issue by teryyoung** [brentp/bwa-meth#89]
when i run:
`bwameth.py`` --reference ref.fa t_R1.fastq.gz t_R2.fastq.gz -t 12 | samtools view -b - > bwa-meth.bam`
--------------------
there's exception that:

_Found BWA MEM index
running: /share/home/yangLab/yangyi/miniconda3/bin/python /share/apps/softwares/bwa-meth-master/bwameth.py c2t t_R1.fastq.gz t_R2.fastq.gz |bwa mem -T 40 -B 2 -L 10 -CM -U 100 -p -R '@RG\tID:t_R\tSM:t_R' -t 12  ref.fa.bwameth.c2t /dev/stdin
--------------------
Traceback (most recent call last):
  File "/share/apps/softwares/bwa-meth-master/bwameth.py", line 559, in <module>
    main(sys.argv[1:])
  File "/share/apps/softwares/bwa-meth-master/bwameth.py", line 550, in main
    bwa_mem(args.reference, conv_fqs_cmd, ' '.join(map(str, pass_through_args)),
  File "/share/apps/softwares/bwa-meth-master/bwameth.py", line 370, in bwa_mem
    as_bam(cmd, fa, set_as_failed, do_not_penalize_chimeras)
  File "/share/apps/softwares/bwa-meth-master/bwameth.py", line 380, in as_bam
    sam_iter = nopen_keep_parent_stdin(pfile, 'r')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/apps/softwares/bwa-meth-master/bwameth.py", line 60, in nopen_keep_parent_stdin
    preexec_fn=toolshed.files.prefunc,
               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'toolshed.files' has no attribute 'prefunc'
[main_samview] fail to read the header from "-"._

##my toolshed version is 0.4.0, which version of toolshed should i use?

**Comment by brentp** [comment]
you'll need a newer version of toolshed: https://github.com/brentp/bwa-meth/issues/56#issuecomment-1011812977

**Comment by teryyoung** [comment]
@brentp thanks very much, I got a lateset version toolshed, and it worked.
